/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as InfomationRouteImport } from './routes/infomation'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsTutorialIndexRouteImport } from './routes/docs/tutorial/index'
import { Route as DocsTutorialCreateAProjectRouteImport } from './routes/docs/tutorial/create-a-project'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const InfomationRoute = InfomationRouteImport.update({
  id: '/infomation',
  path: '/infomation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTutorialIndexRoute = DocsTutorialIndexRouteImport.update({
  id: '/tutorial/',
  path: '/tutorial/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTutorialCreateAProjectRoute =
  DocsTutorialCreateAProjectRouteImport.update({
    id: '/tutorial/create-a-project',
    path: '/tutorial/create-a-project',
    getParentRoute: () => DocsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/infomation': typeof InfomationRoute
  '/templates': typeof TemplatesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/tutorial/create-a-project': typeof DocsTutorialCreateAProjectRoute
  '/docs/tutorial/': typeof DocsTutorialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/infomation': typeof InfomationRoute
  '/templates': typeof TemplatesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs': typeof DocsIndexRoute
  '/docs/tutorial/create-a-project': typeof DocsTutorialCreateAProjectRoute
  '/docs/tutorial': typeof DocsTutorialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/infomation': typeof InfomationRoute
  '/templates': typeof TemplatesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/tutorial/create-a-project': typeof DocsTutorialCreateAProjectRoute
  '/docs/tutorial/': typeof DocsTutorialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/infomation'
    | '/templates'
    | '/docs/getting-started'
    | '/docs/'
    | '/docs/tutorial/create-a-project'
    | '/docs/tutorial/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/infomation'
    | '/templates'
    | '/docs/getting-started'
    | '/docs'
    | '/docs/tutorial/create-a-project'
    | '/docs/tutorial'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/infomation'
    | '/templates'
    | '/docs/getting-started'
    | '/docs/'
    | '/docs/tutorial/create-a-project'
    | '/docs/tutorial/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  InfomationRoute: typeof InfomationRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infomation': {
      id: '/infomation'
      path: '/infomation'
      fullPath: '/infomation'
      preLoaderRoute: typeof InfomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tutorial/': {
      id: '/docs/tutorial/'
      path: '/tutorial'
      fullPath: '/docs/tutorial/'
      preLoaderRoute: typeof DocsTutorialIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tutorial/create-a-project': {
      id: '/docs/tutorial/create-a-project'
      path: '/tutorial/create-a-project'
      fullPath: '/docs/tutorial/create-a-project'
      preLoaderRoute: typeof DocsTutorialCreateAProjectRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsTutorialCreateAProjectRoute: typeof DocsTutorialCreateAProjectRoute
  DocsTutorialIndexRoute: typeof DocsTutorialIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsTutorialCreateAProjectRoute: DocsTutorialCreateAProjectRoute,
  DocsTutorialIndexRoute: DocsTutorialIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  InfomationRoute: InfomationRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
