/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsHowToCreateYourTemplateIndexRouteImport } from './routes/docs/how-to-create-your-template/index'
import { Route as DocsHowToCreateYourTemplateQuickStartRouteImport } from './routes/docs/how-to-create-your-template/quick-start'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const DocsHowToCreateYourTemplateIndexRoute =
  DocsHowToCreateYourTemplateIndexRouteImport.update({
    id: '/how-to-create-your-template/',
    path: '/how-to-create-your-template/',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsHowToCreateYourTemplateQuickStartRoute =
  DocsHowToCreateYourTemplateQuickStartRouteImport.update({
    id: '/how-to-create-your-template/quick-start',
    path: '/how-to-create-your-template/quick-start',
    getParentRoute: () => DocsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/how-to-create-your-template/quick-start': typeof DocsHowToCreateYourTemplateQuickStartRoute
  '/docs/how-to-create-your-template/': typeof DocsHowToCreateYourTemplateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs': typeof DocsIndexRoute
  '/docs/how-to-create-your-template/quick-start': typeof DocsHowToCreateYourTemplateQuickStartRoute
  '/docs/how-to-create-your-template': typeof DocsHowToCreateYourTemplateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/how-to-create-your-template/quick-start': typeof DocsHowToCreateYourTemplateQuickStartRoute
  '/docs/how-to-create-your-template/': typeof DocsHowToCreateYourTemplateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/templates'
    | '/docs/$'
    | '/docs/getting-started'
    | '/docs/'
    | '/docs/how-to-create-your-template/quick-start'
    | '/docs/how-to-create-your-template/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/templates'
    | '/docs/$'
    | '/docs/getting-started'
    | '/docs'
    | '/docs/how-to-create-your-template/quick-start'
    | '/docs/how-to-create-your-template'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/templates'
    | '/docs/$'
    | '/docs/getting-started'
    | '/docs/'
    | '/docs/how-to-create-your-template/quick-start'
    | '/docs/how-to-create-your-template/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/how-to-create-your-template/': {
      id: '/docs/how-to-create-your-template/'
      path: '/how-to-create-your-template'
      fullPath: '/docs/how-to-create-your-template/'
      preLoaderRoute: typeof DocsHowToCreateYourTemplateIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/how-to-create-your-template/quick-start': {
      id: '/docs/how-to-create-your-template/quick-start'
      path: '/how-to-create-your-template/quick-start'
      fullPath: '/docs/how-to-create-your-template/quick-start'
      preLoaderRoute: typeof DocsHowToCreateYourTemplateQuickStartRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsHowToCreateYourTemplateQuickStartRoute: typeof DocsHowToCreateYourTemplateQuickStartRoute
  DocsHowToCreateYourTemplateIndexRoute: typeof DocsHowToCreateYourTemplateIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsHowToCreateYourTemplateQuickStartRoute:
    DocsHowToCreateYourTemplateQuickStartRoute,
  DocsHowToCreateYourTemplateIndexRoute: DocsHowToCreateYourTemplateIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
